/**
 * Git date utilities for documentation pages.
 *
 * Provides access to build-time-extracted git dates (created + last updated)
 * for each documentation page. The data is generated by
 * `scripts/generate-git-dates.mjs` during the prebuild step.
 *
 * Usage:
 *   import { getPageDates } from "@/lib/gitDates"
 *   const dates = getPageDates("docs/get-started")
 *   // { created: "2024-01-15T10:30:00+01:00", updated: "2025-12-01T14:22:00+01:00" }
 */

import gitDatesData from "@/data/gitDates.json"

/** ISO 8601 date string or null if the page has no git history. */
export type ISODateString = string | null

/** Git dates for a single documentation page. */
export interface PageGitDates {
  /** Date of the first commit that introduced this page. */
  created: ISODateString
  /** Date of the most recent commit that modified this page. */
  updated: ISODateString
}

/** The full git dates index keyed by page slug (e.g. "docs/get-started"). */
export type GitDatesIndex = Record<string, PageGitDates>

const gitDates: GitDatesIndex = gitDatesData as GitDatesIndex

/**
 * Look up git dates for a documentation page by its slug.
 *
 * @param slug - The page slug, e.g. "docs/get-started" or "docs/woql-basics"
 * @returns The page's git dates, or { created: null, updated: null } if not found.
 */
export function getPageDates(slug: string): PageGitDates {
  return gitDates[slug] ?? { created: null, updated: null }
}

/**
 * Get all page git dates (the full index).
 * Useful for sitemap generation or bulk operations.
 */
export function getAllPageDates(): GitDatesIndex {
  return gitDates
}

/**
 * Format an ISO date string for display.
 * Returns a human-readable date like "15 Jan 2024" or null if the date is unavailable.
 *
 * @param isoDate - ISO 8601 date string or null
 * @param locale - BCP 47 locale string (default: "en-GB" for international English)
 */
export function formatPageDate(isoDate: ISODateString, locale: string = "en-GB"): string | null {
  if (!isoDate) {
    return null
  }

  try {
    const date = new Date(isoDate)
    return date.toLocaleDateString(locale, {
      day: "numeric",
      month: "short",
      year: "numeric",
    })
  } catch {
    return null
  }
}
