/**
 * run-intent-assertions.test.mjs — Intent-driven HTTP assertion test suite.
 *
 * Reads intent-assertions.json (generated by generate-intent-assertions.mjs)
 * and the corresponding page.md files to execute HTTP requests with enriched
 * assertions from intent YAML annotations.
 *
 * This extends run-http-examples.test.mjs by:
 *   1. Using intent YAML expected_outcome fields for assertion data
 *   2. Supporting tolerance modes: exact, contains, count_gte, non_empty
 *   3. Validating response BODIES, not just status codes
 *
 * Run: npx mocha scripts/docs-example-tests/run-intent-assertions.test.mjs --timeout 60000
 * Or:  npm run test:intent-assertions
 */

import { readFileSync, existsSync } from "node:fs"
import { join, dirname, basename } from "node:path"
import { fileURLToPath } from "node:url"
import assert from "node:assert/strict"

const __dirname = fileURLToPath(new URL(".", import.meta.url))
const REPO_ROOT = join(__dirname, "../..")
const DOCS_DIR = join(REPO_ROOT, "src/app/docs")
const MANIFEST_PATH = join(__dirname, "intent-assertions.json")
const SERVER_URL = process.env.TERMINUSDB_URL || "http://localhost:6363"
const AUTH_USER = process.env.TERMINUSDB_USER || "admin"
const AUTH_KEY = process.env.TERMINUSDB_KEY || "root"

// ============================================================================
// Manifest loading
// ============================================================================

function loadManifest() {
  if (!existsSync(MANIFEST_PATH)) {
    return null
  }
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"))
  } catch {
    return null
  }
}

// ============================================================================
// HTTP helpers
// ============================================================================

function buildAuthHeader() {
  return "Basic " + Buffer.from(`${AUTH_USER}:${AUTH_KEY}`).toString("base64")
}

async function isServerReachable() {
  try {
    const response = await fetch(`${SERVER_URL}/api/info`, {
      headers: { Authorization: buildAuthHeader() },
      signal: AbortSignal.timeout(5000),
    })
    return response.ok || response.status === 401
  } catch {
    return false
  }
}

// ============================================================================
// Markdoc http-example parser (reused from run-http-examples.test.mjs)
// ============================================================================

function parseAttributes(attrString) {
  const attrs = {}
  const attrPattern = /([\w-]+)\s*=\s*(?:"([^"]*?)"|'([^']*?)'|(\S+))/g
  let m
  while ((m = attrPattern.exec(attrString)) !== null) {
    attrs[m[1]] = m[2] ?? m[3] ?? m[4]
  }
  return attrs
}

function parseHttpExamples(content) {
  const steps = []
  const tagOpenPattern = /\{%\s*(http-example(?:-cleanup)?)\s+((?:[^%]|%(?!\}))*?)(\/?)\s*%\}/g
  let match

  while ((match = tagOpenPattern.exec(content)) !== null) {
    const tagName = match[1]
    const attrString = match[2]
    const isSelfClosing = match[3] === "/"
    const tagEnd = match.index + match[0].length

    const attrs = parseAttributes(attrString)
    if (attrs.runnable === "false") continue

    if (tagName === "http-example-cleanup") {
      steps.push({
        index: steps.length,
        isCleanup: true,
        fixture: attrs.fixture || null,
        method: "DELETE",
        path: `/api/db/${AUTH_USER}/${attrs.fixture}`,
      })
    } else if (isSelfClosing) {
      steps.push({
        index: steps.length,
        method: attrs.method || "GET",
        path: attrs.path || "",
        headers: attrs.headers ? parseJsonSafe(attrs.headers) : undefined,
        body: null,
        fixture: attrs.fixture || undefined,
        isCleanup: false,
      })
    } else {
      const closePattern = /\{%\s*\/http-example\s*%\}/g
      closePattern.lastIndex = tagEnd
      const closeMatch = closePattern.exec(content)

      let body = null
      if (closeMatch) {
        const innerContent = content.slice(tagEnd, closeMatch.index).trim()

        // Strip http-expected and http-woql child tags
        let bodyContent = innerContent
        const expectedMatch = innerContent.match(
          /\{%\s*http-expected\s*%\}([\s\S]*?)\{%\s*\/http-expected\s*%\}/
        )
        if (expectedMatch) {
          bodyContent = innerContent.slice(0, expectedMatch.index).trim()
        }
        const woqlMatch = bodyContent.match(
          /\{%\s*http-woql\s*%\}[\s\S]*?\{%\s*\/http-woql\s*%\}/
        )
        if (woqlMatch) {
          bodyContent = bodyContent.slice(woqlMatch.index + woqlMatch[0].length).trim()
          const fenceMatch = bodyContent.match(/^```(?:json)?\s*\n([\s\S]*?)\n```$/)
          if (fenceMatch) {
            bodyContent = fenceMatch[1].trim()
          }
        }

        body = bodyContent || null
        tagOpenPattern.lastIndex = closeMatch.index + closeMatch[0].length
      }

      steps.push({
        index: steps.length,
        method: attrs.method || "GET",
        path: attrs.path || "",
        headers: attrs.headers ? parseJsonSafe(attrs.headers) : undefined,
        body,
        fixture: attrs.fixture || undefined,
        isCleanup: false,
      })
    }
  }

  return steps
}

function parseJsonSafe(str) {
  try {
    return JSON.parse(str)
  } catch {
    return str
  }
}

// ============================================================================
// Assertion engine
// ============================================================================

/**
 * Apply an intent assertion against an HTTP response.
 * Returns { passed: boolean, errors: string[] }
 */
function applyIntentAssertion(intentAssertion, responseStatus, responseBody) {
  const errors = []

  switch (intentAssertion.type) {
    case "status_code": {
      const expected = intentAssertion.expected_status || 200
      if (responseStatus !== expected) {
        errors.push(
          `Expected status ${expected}, got ${responseStatus}: ${responseBody.slice(0, 200)}`
        )
      }
      break
    }

    case "response_body": {
      // First check we got a 2xx
      if (responseStatus < 200 || responseStatus >= 300) {
        errors.push(`Expected 2xx status, got ${responseStatus}: ${responseBody.slice(0, 200)}`)
        break
      }

      const tolerance = intentAssertion.tolerance || "exact"
      const expectedValue = intentAssertion.expected_value

      switch (tolerance) {
        case "exact": {
          if (!expectedValue) break
          try {
            const actual = JSON.parse(responseBody)
            const expected = typeof expectedValue === "string"
              ? JSON.parse(expectedValue)
              : expectedValue

            // For WOQL responses, unwrap bindings
            let compareTarget = actual
            if (Array.isArray(expected) && !Array.isArray(actual) && Array.isArray(actual.bindings)) {
              compareTarget = actual.bindings.map(unwrapTypedValues)
            }

            const mismatches = findSubsetMismatches(expected, compareTarget)
            if (mismatches.length > 0) {
              errors.push(`Exact match failed:\n    ${mismatches.join("\n    ")}`)
            }
          } catch (e) {
            errors.push(`JSON parse error for exact match: ${e.message}`)
          }
          break
        }

        case "contains": {
          if (!expectedValue) break
          // Try JSON subset match first, fall back to string contains
          try {
            const actual = JSON.parse(responseBody)
            const expected = typeof expectedValue === "string"
              ? JSON.parse(expectedValue)
              : expectedValue

            let compareTarget = actual
            if (Array.isArray(expected) && !Array.isArray(actual) && Array.isArray(actual.bindings)) {
              compareTarget = actual.bindings.map(unwrapTypedValues)
            }

            const mismatches = findSubsetMismatches(expected, compareTarget)
            if (mismatches.length > 0) {
              errors.push(`Subset match failed:\n    ${mismatches.join("\n    ")}`)
            }
          } catch {
            // Fall back to string containment
            const searchStr = typeof expectedValue === "string"
              ? expectedValue
              : JSON.stringify(expectedValue)
            if (!responseBody.includes(searchStr)) {
              errors.push(
                `Response does not contain "${searchStr.slice(0, 100)}"\n    Got: ${responseBody.slice(0, 200)}`
              )
            }
          }
          break
        }

        case "count_gte": {
          if (!expectedValue) break
          try {
            const actual = JSON.parse(responseBody)
            // Extract count from description like "Array of 6 items: ..."
            const countMatch = String(expectedValue).match(/(\d+)/)
            if (countMatch) {
              const minCount = parseInt(countMatch[1], 10)
              const arr = Array.isArray(actual) ? actual
                : (actual.bindings && Array.isArray(actual.bindings)) ? actual.bindings
                  : null
              if (arr === null) {
                errors.push(`Expected array response for count_gte, got ${typeof actual}`)
              } else if (arr.length < minCount) {
                errors.push(`Expected array length >= ${minCount}, got ${arr.length}`)
              }
            }
          } catch (e) {
            errors.push(`JSON parse error for count_gte: ${e.message}`)
          }
          break
        }

        case "non_empty": {
          if (!responseBody || responseBody.trim() === "" || responseBody.trim() === "null") {
            errors.push("Expected non-empty response body, got empty or null")
          }
          try {
            const actual = JSON.parse(responseBody)
            if (actual === null || actual === undefined) {
              errors.push("Expected non-null JSON response, got null")
            } else if (Array.isArray(actual) && actual.length === 0) {
              errors.push("Expected non-empty array, got []")
            } else if (typeof actual === "object" && Object.keys(actual).length === 0) {
              errors.push("Expected non-empty object, got {}")
            }
          } catch {
            // Non-JSON response — string check is sufficient
          }
          break
        }

        default:
          // Unknown tolerance — just check non-empty
          if (!responseBody || responseBody.trim() === "") {
            errors.push(`Expected non-empty response (tolerance: ${tolerance})`)
          }
      }
      break
    }

    case "output_contains": {
      if (responseStatus < 200 || responseStatus >= 300) {
        errors.push(`Expected 2xx status, got ${responseStatus}`)
        break
      }
      const searchStr = intentAssertion.expected_value
      if (searchStr && !responseBody.includes(searchStr)) {
        errors.push(
          `Response does not contain "${searchStr}"\n    Got: ${responseBody.slice(0, 200)}`
        )
      }
      break
    }

    case "state_change": {
      // For state changes (e.g., clone), just verify 2xx
      if (responseStatus < 200 || responseStatus >= 300) {
        errors.push(`Expected 2xx for state change, got ${responseStatus}`)
      }
      break
    }

    case "non_empty": {
      if (responseStatus < 200 || responseStatus >= 300) {
        errors.push(`Expected 2xx, got ${responseStatus}`)
        break
      }
      if (!responseBody || responseBody.trim() === "" || responseBody.trim() === "null") {
        errors.push("Expected non-empty response body")
      }
      break
    }

    default:
      // Fallback: just check 2xx
      if (responseStatus < 200 || responseStatus >= 300) {
        errors.push(`Expected 2xx, got ${responseStatus}: ${responseBody.slice(0, 200)}`)
      }
  }

  return { passed: errors.length === 0, errors }
}

/**
 * Unwrap typed RDF values in WOQL bindings:
 * {"@value": "x", "@type": "xsd:string"} → "x"
 */
function unwrapTypedValues(row) {
  const unwrapped = {}
  for (const [key, val] of Object.entries(row)) {
    if (val && typeof val === "object" && "@value" in val) {
      unwrapped[key] = val["@value"]
    } else {
      unwrapped[key] = val
    }
  }
  return unwrapped
}

/**
 * Subset match: every field in expected must exist in actual with matching value.
 * Extra fields in actual are tolerated.
 * "*" wildcard matches any non-null value.
 */
function findSubsetMismatches(expected, actual, path = "$") {
  const mismatches = []

  if (expected === "*") {
    if (actual === null || actual === undefined) {
      mismatches.push(`${path}: expected any non-null value, got ${JSON.stringify(actual)}`)
    }
    return mismatches
  }

  if (Array.isArray(expected)) {
    if (!Array.isArray(actual)) {
      mismatches.push(`${path}: expected array, got ${typeof actual}`)
    } else {
      for (let i = 0; i < expected.length; i++) {
        if (i >= actual.length) {
          mismatches.push(`${path}[${i}]: missing in response (array too short)`)
        } else {
          mismatches.push(...findSubsetMismatches(expected[i], actual[i], `${path}[${i}]`))
        }
      }
    }
  } else if (expected !== null && typeof expected === "object") {
    if (actual === null || typeof actual !== "object" || Array.isArray(actual)) {
      mismatches.push(`${path}: expected object, got ${JSON.stringify(actual)?.slice(0, 50)}`)
    } else {
      for (const key of Object.keys(expected)) {
        if (!(key in actual)) {
          mismatches.push(`${path}.${key}: missing in response`)
        } else {
          mismatches.push(...findSubsetMismatches(expected[key], actual[key], `${path}.${key}`))
        }
      }
    }
  } else {
    if (expected !== actual) {
      mismatches.push(`${path}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`)
    }
  }

  return mismatches
}

// ============================================================================
// Execution helpers
// ============================================================================

async function deleteDb(dbName) {
  const url = `${SERVER_URL}/api/db/${AUTH_USER}/${dbName}`
  try {
    await fetch(url, {
      method: "DELETE",
      headers: { Authorization: buildAuthHeader() },
      signal: AbortSignal.timeout(10000),
    })
  } catch {
    // Ignore
  }
}

/**
 * Detect and execute quickstart-clone operations from page content.
 * Returns the list of database names that were cloned.
 */
async function executeClones(content) {
  const cloned = []
  const clonePattern = /\{%\s*quickstart-clone\s+((?:[^%]|%(?!\}))*?)\/?%\}/g
  let match

  while ((match = clonePattern.exec(content)) !== null) {
    const attrs = parseAttributes(match[1])
    const remoteUrl = attrs.remoteUrl || "https://data.terminusdb.org/public/star-wars"
    const localPath = attrs.localPath || "star-wars"

    await deleteDb(localPath)

    const cloneUrl = `${SERVER_URL}/api/clone/${AUTH_USER}/${localPath}`
    const response = await fetch(cloneUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: buildAuthHeader(),
        "Authorization-Remote": "Token anonymous_user_do_not_delete",
      },
      body: JSON.stringify({
        remote_url: remoteUrl,
        label: localPath,
        comment: `Cloned for intent test`,
      }),
      signal: AbortSignal.timeout(60000),
    })

    if (response.ok) {
      cloned.push(localPath)
    } else {
      const text = await response.text()
      throw new Error(`Clone failed for ${localPath}: ${response.status} ${text}`)
    }
  }

  return cloned
}

async function executeStep(step) {
  const url = `${SERVER_URL}${step.path}`
  const headers = { Authorization: buildAuthHeader() }
  if (step.body) headers["Content-Type"] = "application/json"
  if (step.headers && typeof step.headers === "object") {
    Object.assign(headers, step.headers)
  }

  const isClone = step.path && step.path.includes("/api/clone/")
  const timeout = isClone ? 60000 : 15000

  const response = await fetch(url, {
    method: step.method,
    headers,
    body: step.body || undefined,
    signal: AbortSignal.timeout(timeout),
  })

  const responseText = await response.text()
  return { status: response.status, body: responseText }
}

// ============================================================================
// Mocha test suite
// ============================================================================

const manifest = loadManifest()

describe("intent-driven HTTP assertions", function () {
  let serverAvailable = false

  before(async function () {
    this.timeout(10000)

    if (!manifest) {
      console.log("    ⚠ No intent-assertions.json found.")
      console.log("    Run: node scripts/docs-example-tests/generate-intent-assertions.mjs")
      return
    }

    serverAvailable = await isServerReachable()
    if (!serverAvailable) {
      console.log(`    TerminusDB not reachable at ${SERVER_URL}. Skipping.`)
    }
  })

  if (!manifest || !manifest.pages || Object.keys(manifest.pages).length === 0) {
    it("no intent assertions to run (generate manifest first)", function () {
      this.skip()
    })
  } else {
    for (const [slug, pageData] of Object.entries(manifest.pages)) {
      describe(`page: ${slug}`, function () {
        it(`validates ${pageData.testable_assertions} intent assertions`, async function () {
          if (!serverAvailable) { this.skip(); return }
          this.timeout(120000)

          // Load the page source to extract http-example steps
          const pagePath = join(DOCS_DIR, slug, "page.md")
          if (!existsSync(pagePath)) {
            console.log(`      ⚠ Page not found: ${pagePath}`)
            this.skip()
            return
          }

          const content = readFileSync(pagePath, "utf-8")
          const steps = parseHttpExamples(content)

          if (steps.length === 0) {
            console.log(`      ⚠ No http-example steps extracted from ${slug}`)
            this.skip()
            return
          }

          // Execute any quickstart-clone operations first
          const clonedDbs = await executeClones(content)

          // Detect databases the sequence creates via HTTP and pre-delete
          const createdDbs = detectCreatedDatabases(steps)
          for (const db of createdDbs) {
            if (!clonedDbs.includes(db)) {
              await deleteDb(db)
            }
          }

          // Detect databases USED but not CREATED — pre-create them as fixtures
          const usedDbs = detectUsedDatabases(steps)
          const allProvidedDbs = [...createdDbs, ...clonedDbs]
          for (const db of usedDbs) {
            if (!allProvidedDbs.includes(db)) {
              await deleteDb(db)
              const createUrl = `${SERVER_URL}/api/db/${AUTH_USER}/${db}`
              await fetch(createUrl, {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: buildAuthHeader(),
                },
                body: JSON.stringify({ label: db, comment: "Intent test fixture" }),
                signal: AbortSignal.timeout(10000),
              })
              allProvidedDbs.push(db)
            }
          }

          // Setup fixture if needed
          const fixture = steps.find(s => s.fixture)?.fixture
          if (fixture && !allProvidedDbs.includes(fixture)) {
            await deleteDb(fixture)
            const createUrl = `${SERVER_URL}/api/db/${AUTH_USER}/${fixture}`
            await fetch(createUrl, {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                Authorization: buildAuthHeader(),
              },
              body: JSON.stringify({ label: fixture, comment: "Intent test fixture" }),
              signal: AbortSignal.timeout(10000),
            })
          }

          // Build assertion lookup by step index.
          // Steps = only RUNNABLE http-examples (runnable=false are skipped).
          // Assertions use block_index from the intent YAML (includes all blocks).
          const intentPath = join(REPO_ROOT, "intent", `${slug}.yaml`)
          const runnableBlockIndices = detectRunnableBlockIndices(content, intentPath)
          const assertionMap = new Map()

          if (runnableBlockIndices.length > 0) {
            for (let si = 0; si < runnableBlockIndices.length; si++) {
              const bi = runnableBlockIndices[si]
              const assertion = pageData.assertions.find(a => a.block_index === bi)
              if (assertion) assertionMap.set(si, assertion)
            }
          } else {
            // Fallback: 1:1 mapping by order
            const sorted = [...pageData.assertions].sort((a, b) => a.block_index - b.block_index)
            sorted.forEach((a, i) => assertionMap.set(i, a))
          }

          const results = []
          let failed = false

          try {
            for (let i = 0; i < steps.length; i++) {
              const step = steps[i]
              if (step.isCleanup) {
                await deleteDb(step.fixture)
                results.push({ index: i, method: "DELETE", path: `(cleanup)`, passed: true })
                continue
              }

              const response = await executeStep(step)
              const intentAssertion = assertionMap.get(i)

              if (intentAssertion) {
                // Apply enriched intent assertion
                const result = applyIntentAssertion(
                  intentAssertion,
                  response.status,
                  response.body
                )
                results.push({
                  index: i,
                  method: step.method,
                  path: step.path,
                  httpStatus: response.status,
                  passed: result.passed,
                  errors: result.errors,
                  assertionType: intentAssertion.type,
                  tolerance: intentAssertion.tolerance,
                })

                if (!result.passed) {
                  failed = true
                  break
                }
              } else {
                // No intent assertion — just verify 2xx
                const passed = response.status >= 200 && response.status < 300
                results.push({
                  index: i,
                  method: step.method,
                  path: step.path,
                  httpStatus: response.status,
                  passed,
                  errors: passed ? [] : [`Got ${response.status}`],
                  assertionType: "default_2xx",
                })

                if (!passed) {
                  failed = true
                  break
                }
              }
            }
          } finally {
            // Cleanup all databases used by the test
            for (const db of allProvidedDbs) {
              await deleteDb(db)
            }
            if (fixture && !allProvidedDbs.includes(fixture)) {
              await deleteDb(fixture)
            }
          }

          // Report results
          for (const r of results) {
            const icon = r.passed ? "✓" : "✗"
            const assertLabel = r.assertionType ? ` [${r.assertionType}]` : ""
            console.log(
              `      ${icon} [${r.index + 1}/${steps.length}] ${r.method} ${r.path?.slice(0, 50)} → ${r.httpStatus}${assertLabel}`
            )
          }

          if (failed) {
            const failures = results.filter(r => !r.passed)
            const details = failures.map(f => {
              const errList = f.errors.map(e => `    - ${e}`).join("\n")
              return `Step ${f.index + 1}: ${f.method} ${f.path}\n${errList}`
            }).join("\n\n")
            assert.fail(`Intent assertions failed:\n\n${details}`)
          }
        })
      })
    }
  }
})

/**
 * Determine which intent YAML block_indices correspond to runnable http-examples.
 *
 * Parses the page content to find ALL http-example tags in order, tracking which
 * are runnable (not marked runnable=false). Then maps the position of each
 * http-example tag to the corresponding intent YAML block_index.
 *
 * Returns the block_index values for runnable http-examples only.
 */
function detectRunnableBlockIndices(content, intentPath) {
  // Get the ordered list of http-example block_indices from the intent YAML
  let httpBlockIndices = []
  if (intentPath && existsSync(intentPath)) {
    try {
      const intentContent = readFileSync(intentPath, "utf-8")
      const blocks = []
      const blockPattern = /- block_index:\s*(\d+)[\s\S]*?type:\s*(\S+)/g
      let bm
      while ((bm = blockPattern.exec(intentContent)) !== null) {
        blocks.push({ block_index: Number(bm[1]), type: bm[2] })
      }
      httpBlockIndices = blocks
        .filter(b => b.type === "http-example")
        .map(b => b.block_index)
    } catch { /* fall through */ }
  }

  if (httpBlockIndices.length === 0) return []

  // Parse page content to find http-example tags and which are runnable
  const tagPattern = /\{%\s*http-example(?:-cleanup)?\s+((?:[^%]|%(?!\}))*?)(\/?)\s*%\}/g
  let match
  let httpIdx = 0
  const runnableIndices = []

  while ((match = tagPattern.exec(content)) !== null) {
    const attrs = parseAttributes(match[1])
    if (attrs.runnable !== "false") {
      if (httpIdx < httpBlockIndices.length) {
        runnableIndices.push(httpBlockIndices[httpIdx])
      }
    }
    httpIdx++
  }
  return runnableIndices
}

/**
 * Detect databases that a sequence will CREATE via POST /api/db/{org}/{name}.
 */
function detectCreatedDatabases(steps) {
  const dbs = []
  const dbCreatePattern = /^\/api\/db\/[^/]+\/([^/?]+)/
  const clonePattern = /^\/api\/clone\/[^/]+\/([^/?]+)/
  for (const step of steps) {
    if (step.method === "POST" && step.path) {
      const m = step.path.match(dbCreatePattern) || step.path.match(clonePattern)
      if (m) dbs.push(m[1])
    }
  }
  return [...new Set(dbs)]
}

/**
 * Detect databases that are USED (referenced in paths) but may not be explicitly created.
 */
function detectUsedDatabases(steps) {
  const dbs = new Set()
  const dbPathPattern = /^\/api\/(?:document|branch|diff|apply|log|history|patch|reset|squash)\/[^/]+\/([^/?_][^/?]*)/
  for (const step of steps) {
    if (step.path) {
      const m = step.path.match(dbPathPattern)
      if (m) dbs.add(m[1])
    }
  }
  return [...dbs]
}
