# Build the crate, run the tests, and check the code format.
name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx bun install
      - run: npx bun run build
