name: Publish

on:
  push:
    branches: [ "main" ]
    paths: [ "**", ".github/workflows/publish.yml" ]
  schedule:
    # Nightly at 1am
    - cron: '0 1 * * 0'
  workflow_call:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages-prod"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx bun install
      - run: npx bun run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "out"
          skip_app_build: true
          skip_api_build: true
          output_location: ''
          deployment_environment: ''
